movies_bancodedados_sql/movies/urls.py
from django.urls import path

from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.MovieListView.as_view(), name='index'),  # edite esta linha
    path('search/', views.search_movies, name='search'),
    path('create/', views.create_movie, name='create'),
    path('<int:movie_id>/', views.detail_movie,
         name='detail'), 
    path('update/<int:movie_id>/', views.update_movie, name='update'),
    path('delete/<int:movie_id>/', views.delete_movie, name='delete'),
]

movies_bancodedados_sql/moviesite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

movies_bancodedados_sql/staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

movies_bancodedados_sql/movies/models.py
from django.db import models
from django.conf import settings


class Movie(models.Model):
    name = models.CharField(max_length=255)
    release_year = models.IntegerField()
    poster_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.name} ({self.release_year})'


class Review(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    likes = models.IntegerField(default=0)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

movies_bancodedados_sql/movies/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from .temp_data import movie_data
from django.shortcuts import render, get_object_or_404
from django.views import generic

from .models import Movie

def detail_movie(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    context = {'movie': movie}
    return render(request, 'movies/detail.html', context)


class MovieListView(generic.ListView):
    model = Movie
    template_name = 'movies/index.html'


def search_movies(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        movie_list = Movie.objects.filter(name__icontains=search_term)
        context = {"movie_list": movie_list}
    return render(request, 'movies/search.html', context)



def create_movie(request):
    if request.method == 'POST':
        movie_name = request.POST['name']
        movie_release_year = request.POST['release_year']
        movie_poster_url = request.POST['poster_url']
        movie = Movie(name=movie_name,
                      release_year=movie_release_year,
                      poster_url=movie_poster_url)
        movie.save()
        return HttpResponseRedirect(
            reverse('movies:detail', args=(movie.id, )))
    else:
        return render(request, 'movies/create.html', {})

def update_movie(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)

    if request.method == "POST":
        movie.name = request.POST['name']
        movie.release_year = request.POST['release_year']
        movie_poster_url = request.POST['poster_url']
        movie.save()
        return HttpResponseRedirect(
            reverse('movies:detail', args=(movie.id, )))

    context = {'movie': movie}
    return render(request, 'movies/update.html', context)


def delete_movie(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)

    if request.method == "POST":
        movie.delete()
        return HttpResponseRedirect(reverse('movies:index'))

    context = {'movie': movie}
    return render(request, 'movies/delete.html', context)

movies_bancodedados_sql/staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

movies_bancodedados_sql/movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Filme</h2>
<form method="POST" action="{% url 'movies:create' %}">
    {% csrf_token %}
    <p>
        <label for="id_name">Título:</label>
        <input type="text" name="name" id="id_name" />
    </p>
    <p>
        <label for="id_release_year">Ano de Lançamento:</label>
        <input type="number" name="release_year" id="id_release_year" />
    </p>
    <p>
        <label for="id_poster_url">URL do Poster:</label>
        <input type="url" name="poster_url" id="id_poster_url" />
    </p>
    <button type="submit">Criar</button>
</form>

{% endblock content %}

movies_bancodedados_sql/movies/templates/movies/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'movies:delete' movie.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o filme "{{ movie.name }} ({{ movie.release_year }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

movies_bancodedados_sql/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block title %}
{{ movie.name }} ({{ movie.release_year }}
{% endblock title %}

{% block content %}
<h2>Detalhes do Filme {{ movie.name }} ({{ movie.release_year }})</h2>

<section class="dados-de-filme">
    <img src="{{ movie.poster_url }}" alt="Poster do filme {{ movie.name}}">
    <ul>
        <li>Nome: {{ movie.name }}</li>
        <li>Ano de Lançamento: {{ movie.release_year }} </li>
        <li><a href="{% url 'movies:update' movie.id %}">Editar</a></li>
        <li><a href="{% url 'movies:delete' movie.id %}">Apagar</a></li>
    </ul>
</section>

{% endblock content %}

movies_bancodedados_sql/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Filmes</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'movies:search' %}">Buscar Filmes</a></p>
    <p>Não encontrou o filme? <a href="{% url 'movies:create' %}">Adicionar Novo Filme</a></p>
</section>
{% if movie_list %}
<section class="lista-de-cards">
    {% for movie in movie_list %}
    <article class="card">
        <a href="{% url 'movies:detail' movie.id %}"><img src="{{ movie.poster_url }}"
                alt="Poster do filme {{ movie.name}}"></a>
        <p>{{ movie.name }} ({{ movie.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum filme.</p>
{% endif %}

{% endblock content %}

movies_bancodedados_sql/movies/templates/movies/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Filmes por Nome</h2>
<form action="{% url 'movies:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if movie_list %}
<section class="lista-de-cards">
    {% for movie in movie_list %}
    <article class="card">
        <img src="{{ movie.poster_url }}" alt="Poster do filme {{ movie.name}}">
        <p>{{ movie.name }} ({{ movie.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum filme para a busca.</p>
{% endif %}

{% endblock content %}

movies_bancodedados_sql/movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Filme {{ movie.name }} ({{ movie.release_year}})</h2>
<form method="POST" action="{% url 'movies:update' movie.id%}">
    {% csrf_token %}
    <p>
        <label for="id_name">Título:</label>
        <input type="text" name="name" id="id_name" value="{{ movie.name }}" />
    </p>
    <p>
        <label for=" id_release_year">Ano de Lançamento:</label>
        <input type="number" name="release_year" id="id_release_year" value="{{ movie.release_year }}" />
    </p>
    <p>
        <label for=" id_poster_url">URL do Poster:</label>
        <input type="url" name="poster_url" id="id_poster_url" value="{{movie.poster_url}}" />
    </p>
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

movies_bancodedados_sql/staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
{% endblock content %}

movies_bancodedados_sql/staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Watch that film!</i></h1>
<p>A Página para Comunidade Resenhadora de Filmes</p>
{% endblock content %}

movies_bancodedados_sql/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Watch that film!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.svg' %}"> </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'movies:index' %}">Filmes</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>